'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Prompts
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PowerSolutions.Applications.PowerFlowSolver.Prompts", GetType(Prompts).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 在已经定义的案例中找不到母线标识“{0}”。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property BusKeyNotFound() As String
            Get
                Return ResourceManager.GetString("BusKeyNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 未指定案例文件。请使用 /? 参数以查看帮助。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property CaseFileMissing() As String
            Get
                Return ResourceManager.GetString("CaseFileMissing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 用法：
        '''PowerFlowSolver /Case:输入文件 [/Report:报告文件] [选项]
        '''其中，
        '''  输入文件  包含了带求解的网络案例信息的输入文件。
        '''  报告文件  指定了输出文本报告的路径，
        '''            如果没有指定，会将报告输出至控制台。
        '''“选项”包括
        '''  /ANSI     指示输出文件应使用ANSI/多字节字符集
        '''            编码系统。注意此操作不会影响输入文件
        '''            的编码检测。在不同语言的操作系统中有
        '''            可能引起乱码。如果未指定此选项，则输
        '''            出文件使用 Unicode 字符集。
        '''
        '''如果没有指定报告文件，会将报告输出至控制台。
        ''' 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property CommandLineUsage() As String
            Get
                Return ResourceManager.GetString("CommandLineUsage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 在此处重新指定求解方式将导致求解器特性被重置。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property DuplicateSolverInstruction() As String
            Get
                Return ResourceManager.GetString("DuplicateSolverInstruction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 文件分析完毕。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property FileParseComplete() As String
            Get
                Return ResourceManager.GetString("FileParseComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 解析行{0}时发生错误：{1} 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property FileParseError() As String
            Get
                Return ResourceManager.GetString("FileParseError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 行{0}：{1} 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property FileParseWarning() As String
            Get
                Return ResourceManager.GetString("FileParseWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 已保存：{0}。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property FileSaveComplete() As String
            Get
                Return ResourceManager.GetString("FileSaveComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 无效的参数：{0}。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property InvalidArgument1() As String
            Get
                Return ResourceManager.GetString("InvalidArgument1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 无效的指令”{0}“。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property InvalidInstruction1() As String
            Get
                Return ResourceManager.GetString("InvalidInstruction1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 无效的求解方式“{0}”。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property InvalidSolver() As String
            Get
                Return ResourceManager.GetString("InvalidSolver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似         累计用时       迭代次数   最大功率误差 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property IterationProgress() As String
            Get
                Return ResourceManager.GetString("IterationProgress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 {0,20}   {1,8}   {2,-12:E4} 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property IterationProgressA() As String
            Get
                Return ResourceManager.GetString("IterationProgressA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 过时的指令。已忽略。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property ObsoleteInstruction() As String
            Get
                Return ResourceManager.GetString("ObsoleteInstruction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 {0}：参数数量不匹配。期望参数数量为{1}；实际参数数量为{2}。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property ParameterCountMismatch3() As String
            Get
                Return ResourceManager.GetString("ParameterCountMismatch3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 
        '''======== 分析报告 ========
        ''' 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property PFReport() As String
            Get
                Return ResourceManager.GetString("PFReport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 电力网络稳态潮流分析报告
        '''案例：{0}
        '''
        '''报告生成于 {1} 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property PFReportMessage1() As String
            Get
                Return ResourceManager.GetString("PFReportMessage1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 
        '''网络统计信息 ==========
        '''母线{0}条。运算总节点{1}个，
        '''其中PQ节点{2}个，PV节点{3}个。
        '''平衡节点：{4}。共计{5}条支路。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property PFReportMessage2() As String
            Get
                Return ResourceManager.GetString("PFReportMessage2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 
        '''求解信息 ==========
        '''{0}
        '''使用{1}迭代{2}次，最大功率误差：{3:E4} p.u.。
        '''迭代次数  最大功率误差 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property PFReportMessage3() As String
            Get
                Return ResourceManager.GetString("PFReportMessage3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 {0,6}    {1,-12:E4} 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property PFReportMessage3A() As String
            Get
                Return ResourceManager.GetString("PFReportMessage3A", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 
        '''节点潮流============
        '''        母线              电压         相位       有功出力     无功出力     有功负载     无功负载
        '''                         [p.u.]       [ °]        [p.u.]       [p.u.]       [p.u.]      [p.u.] 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property PFReportMessage4() As String
            Get
                Return ResourceManager.GetString("PFReportMessage4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 {0} {1,12:G6} {2,12:G6} {3,12:G6} {4,12:G6} {5,12:G6} {6,12:G6} 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property PFReportMessage4A() As String
            Get
                Return ResourceManager.GetString("PFReportMessage4A", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 {0} 孤立母线。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property PFReportMessage4B() As String
            Get
                Return ResourceManager.GetString("PFReportMessage4B", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 
        '''支路潮流============
        '''母线1    --&gt;   母线2            有功(1)    无功(1)    有功(2)    无功(2)   有功损耗   无功损耗   接地有功   接地无功
        '''                                [p.u.]     [p.u.]     [p.u.]     [p.u.]     [p.u.]     [p.u.]     [p.u.]     [p.u.] 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property PFReportMessage5() As String
            Get
                Return ResourceManager.GetString("PFReportMessage5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 {0} {1} {2,10:G4} {3,10:G4} {4,10:G4} {5,10:G4} {6,10:G4} {7,10:G4} {8,10:G4} {9,10:G4} 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property PFReportMessage5A() As String
            Get
                Return ResourceManager.GetString("PFReportMessage5A", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 
        '''总计================
        '''总出力：有功 {0:G6} p.u.，无功 {1:G6} p.u.。
        '''总负载：有功 {2:G6} p.u.，无功 {3:G6} p.u.。
        '''总网损：有功 {4:G6} p.u.，无功 {5:G6} p.u.。
        '''接地支路损耗：有功 {6:G6} p.u.，无功 {7:G6} p.u.。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property PFReportMessage6() As String
            Get
                Return ResourceManager.GetString("PFReportMessage6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 迭代{0}次，全程用时{1}。
        '''{2} 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property SolutionComplete() As String
            Get
                Return ResourceManager.GetString("SolutionComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 求解稳态潮流…… 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property SolutionInProgress() As String
            Get
                Return ResourceManager.GetString("SolutionInProgress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 [{0}]已迭代{1}次，当前误差：{2:G6}，目标误差{3:G6}。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property SolutionProgress() As String
            Get
                Return ResourceManager.GetString("SolutionProgress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 （智能迭代）检测到迭代过程不收敛而中断。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property SolutionStatus_IntelliIterationAbort() As String
            Get
                Return ResourceManager.GetString("SolutionStatus_IntelliIterationAbort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 迭代过程出现问题，可能是由于方程不可解造成的。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property SolutionStatus_IterationFailed() As String
            Get
                Return ResourceManager.GetString("SolutionStatus_IterationFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 已经达到最大允许的迭代次数。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property SolutionStatus_MaxIteration() As String
            Get
                Return ResourceManager.GetString("SolutionStatus_MaxIteration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 迭代过程收敛，求解成功结束。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property SolutionStatus_Success() As String
            Get
                Return ResourceManager.GetString("SolutionStatus_Success", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 剩余时间：少于{0}。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property TimeRemainingEstimation() As String
            Get
                Return ResourceManager.GetString("TimeRemainingEstimation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 64位进程 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property x64Process() As String
            Get
                Return ResourceManager.GetString("x64Process", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
